/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  /*
  xiaojin: [
    'xiaojin/xiaojin-intro',
    {
      type: 'category',
      label: '框架',
      link: {
        type: 'generated-index',
        title: '框架 目录',
        description: "整理的一些关于 框架 的学习笔记，没事自己看看",
        //keywords: ['框架'],
      },
      items: [{
        type: 'autogenerated',
        dirName: 'xiaojin/kuangjia'
      }],
      collapsed: false
    },
    {
      type: 'category',
      label: '数据库',
      link: {
        type: 'generated-index',
        title: '数据库',
        description: "一些数据库，关系型与非关系型",
        //keywords: ['db'],
      },
      items: [{
        type: 'autogenerated',
        dirName: 'xiaojin/db'
      }],
    },
    {
      label: '其它',
      type: 'category',
      link: {
        type: 'generated-index',
        title: '其它东西',
        description: "一些其它的东西，平时会用到",
       // keywords: ['other']
      },
      items: [{
        type: 'autogenerated',
        dirName: 'xiaojin/other'
      }],
      collapsed: false
    },
    {
      label: '资源',
      type: 'category',
      items: [{
        type: 'autogenerated',
        dirName: 'xiaojin/resources'
      }],
      collapsed: true
    }
  ]
  */



  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],


};

module.exports = sidebars;
